# Generated by installer/homebrew/generate.sh — do not edit by hand.
class Maxon < Formula
  desc "Systems language whose compiler is written in itself"
  homepage "https://maxon.dev"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/maxon-lang/maxon/releases/download/v0.2.2/maxon-0.2.2-arm64-macos.tar.gz"
      sha256 "73ff93392201ea85b9724be2e1531621dee6898cfe7f4648cb1e4290f1f7d27a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxon-lang/maxon/releases/download/v0.2.2/maxon-0.2.2-x64-linux.tar.gz"
      sha256 "18a31c997ee8e4eaa5972568efe6ba52cddbf01e36934c80c122fb238f687dbb"
    end
    on_arm do
      url "https://github.com/maxon-lang/maxon/releases/download/v0.2.2/maxon-0.2.2-arm64-linux.tar.gz"
      sha256 "86c9abccd569418f01abebbe31e99b68ff64447432d2164d1ac81b0a43b16554"
    end
  end

  def install
    # ⛔ THE COMPILER, ITS STANDARD LIBRARY AND ITS RUNTIME MUST STAY SIBLINGS. `maxon` finds `stdlib/`
    # and `runtime/` by walking up from its own executable, so installing the binary into `bin` on its
    # own would leave it unable to compile at all. The whole tree goes into libexec, and `bin/maxon` is
    # a symlink to it — the compiler resolves that link, so the walk starts in the real prefix.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"maxon"
  end

  test do
    (testpath/"hello.maxon").write <<~MAXON
      typealias ExitCode = int(0 to 255)

      function main() returns ExitCode
      \tprint("hello\\n")
      \treturn 0
      end 'main'
    MAXON

    assert_match version.to_s, shell_output("#{bin}/maxon version")
    system bin/"maxon", "build", testpath/"hello.maxon", "-o", testpath/"hello"
    assert_equal "hello\n", shell_output(testpath/"hello")
  end
end
