# Generated by installer/homebrew/generate.sh — do not edit by hand.
class Maxon < Formula
  desc "Systems language whose compiler is written in itself"
  homepage "https://maxon.dev"
  version "0.1.1"
  license any_of: ["MIT", "Apache-2.0"]

  # Apple silicon only: there is no x64-macos target yet.
  depends_on arch: :arm64
  url "https://github.com/maxon-lang/maxon/releases/download/v0.1.1/maxon-0.1.1-arm64-macos.tar.gz"
  sha256 "ef681ac596717012c9fcc02d6e0d520ba670f55949c5125e1a0447a1aa678a78"

  def install
    # ⛔ THE COMPILER AND ITS STANDARD LIBRARY MUST STAY SIBLINGS. `maxon` finds `stdlib/` by walking up
    # from its own executable, so installing the binary into `bin` on its own would leave it with no
    # standard library at all. The whole tree goes into libexec, and `bin/maxon` is a symlink to it —
    # the compiler resolves that link, so the walk starts in the real prefix.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"maxon"
  end

  test do
    (testpath/"hello.maxon").write <<~MAXON
      typealias ExitCode = int(0 to 255)

      function main() returns ExitCode
      \tprint("hello\\n")
      \treturn 0
      end 'main'
    MAXON

    assert_match version.to_s, shell_output("#{bin}/maxon version")
    system bin/"maxon", "build", testpath/"hello.maxon", "-o", testpath/"hello"
    assert_equal "hello\n", shell_output(testpath/"hello")
  end
end
