# Generated by installer/homebrew/generate.sh — do not edit by hand.
class Maxon < Formula
  desc "Systems language whose compiler is written in itself"
  homepage "https://maxon.dev"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/maxon-lang/maxon/releases/download/v0.3.1/maxon-0.3.1-arm64-macos.tar.gz"
      sha256 "6ce487336b8613d8f9933a3d3bb69272256d9a6078c1c9f289657ee9be08771c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maxon-lang/maxon/releases/download/v0.3.1/maxon-0.3.1-x64-linux.tar.gz"
      sha256 "b751d19453a1a23b5a81f4da9b544d67a1b3280774baa0f77a9760d7c4dfc473"
    end
    on_arm do
      url "https://github.com/maxon-lang/maxon/releases/download/v0.3.1/maxon-0.3.1-arm64-linux.tar.gz"
      sha256 "e8bbfd9ddd52af59b156d5edc0f1ba2588d2b04d3fe88725efb60231731557d6"
    end
  end

  def install
    # ⛔ THE COMPILER, ITS STANDARD LIBRARY AND ITS RUNTIME MUST STAY SIBLINGS. `maxon` finds `stdlib/`
    # and `runtime/` by walking up from its own executable, so installing the binary into `bin` on its
    # own would leave it unable to compile at all. The whole tree goes into libexec, and `bin/maxon` is
    # a symlink to it — the compiler resolves that link, so the walk starts in the real prefix.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"maxon"
  end

  test do
    (testpath/"hello.maxon").write <<~MAXON
      typealias ExitCode = int(0 to 255)

      function main() returns ExitCode
      \tprint("hello\\n")
      \treturn 0
      end 'main'
    MAXON

    assert_match version.to_s, shell_output("#{bin}/maxon version")
    system bin/"maxon", "build", testpath/"hello.maxon", "-o", testpath/"hello"
    assert_equal "hello\n", shell_output(testpath/"hello")
  end
end
